//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "singleBit",
    "doubleBit"
})
@XmlRootElement(name = "aggregate")
public class Aggregate {

    @XmlElement(name = "single_bit", required = true)
    protected SingleBit singleBit;
    @XmlElement(name = "double_bit", required = true)
    protected DoubleBit doubleBit;

    /**
     * Gets the value of the singleBit property.
     * 
     * @return
     *     possible object is
     *     {@link SingleBit }
     *     
     */
    public SingleBit getSingleBit() {
        return singleBit;
    }

    /**
     * Sets the value of the singleBit property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleBit }
     *     
     */
    public void setSingleBit(SingleBit value) {
        this.singleBit = value;
    }

    /**
     * Gets the value of the doubleBit property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleBit }
     *     
     */
    public DoubleBit getDoubleBit() {
        return doubleBit;
    }

    /**
     * Sets the value of the doubleBit property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleBit }
     *     
     */
    public void setDoubleBit(DoubleBit value) {
        this.doubleBit = value;
    }

}
