//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "autoBoost",
    "autoBoostDefault"
})
@XmlRootElement(name = "clock_policy")
public class ClockPolicy {

    @XmlElement(name = "auto_boost", required = true)
    protected String autoBoost;
    @XmlElement(name = "auto_boost_default", required = true)
    protected String autoBoostDefault;

    /**
     * Gets the value of the autoBoost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoBoost() {
        return autoBoost;
    }

    /**
     * Sets the value of the autoBoost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoBoost(String value) {
        this.autoBoost = value;
    }

    /**
     * Gets the value of the autoBoostDefault property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoBoostDefault() {
        return autoBoostDefault;
    }

    /**
     * Sets the value of the autoBoostDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoBoostDefault(String value) {
        this.autoBoostDefault = value;
    }

}
