//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "currentDm",
    "pendingDm"
})
@XmlRootElement(name = "driver_model")
public class DriverModel {

    @XmlElement(name = "current_dm", required = true)
    protected String currentDm;
    @XmlElement(name = "pending_dm", required = true)
    protected String pendingDm;

    /**
     * Gets the value of the currentDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentDm() {
        return currentDm;
    }

    /**
     * Sets the value of the currentDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentDm(String value) {
        this.currentDm = value;
    }

    /**
     * Gets the value of the pendingDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPendingDm() {
        return pendingDm;
    }

    /**
     * Sets the value of the pendingDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPendingDm(String value) {
        this.pendingDm = value;
    }

}
