//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "currentEcc",
    "pendingEcc"
})
@XmlRootElement(name = "ecc_mode")
public class EccMode {

    @XmlElement(name = "current_ecc", required = true)
    protected String currentEcc;
    @XmlElement(name = "pending_ecc", required = true)
    protected String pendingEcc;

    /**
     * Gets the value of the currentEcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentEcc() {
        return currentEcc;
    }

    /**
     * Sets the value of the currentEcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentEcc(String value) {
        this.currentEcc = value;
    }

    /**
     * Gets the value of the pendingEcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPendingEcc() {
        return pendingEcc;
    }

    /**
     * Sets the value of the pendingEcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPendingEcc(String value) {
        this.pendingEcc = value;
    }

}
