//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "virtualizationMode"
})
@XmlRootElement(name = "gpu_virtualization_mode")
public class GpuVirtualizationMode {

    @XmlElement(name = "virtualization_mode", required = true)
    protected String virtualizationMode;

    /**
     * Gets the value of the virtualizationMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVirtualizationMode() {
        return virtualizationMode;
    }

    /**
     * Sets the value of the virtualizationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVirtualizationMode(String value) {
        this.virtualizationMode = value;
    }

}
