//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imgVersion",
    "oemObject",
    "eccObject",
    "pwrObject"
})
@XmlRootElement(name = "inforom_version")
public class InforomVersion {

    @XmlElement(name = "img_version", required = true)
    protected String imgVersion;
    @XmlElement(name = "oem_object", required = true)
    protected String oemObject;
    @XmlElement(name = "ecc_object", required = true)
    protected String eccObject;
    @XmlElement(name = "pwr_object", required = true)
    protected String pwrObject;

    /**
     * Gets the value of the imgVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgVersion() {
        return imgVersion;
    }

    /**
     * Sets the value of the imgVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgVersion(String value) {
        this.imgVersion = value;
    }

    /**
     * Gets the value of the oemObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOemObject() {
        return oemObject;
    }

    /**
     * Sets the value of the oemObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOemObject(String value) {
        this.oemObject = value;
    }

    /**
     * Gets the value of the eccObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEccObject() {
        return eccObject;
    }

    /**
     * Sets the value of the eccObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEccObject(String value) {
        this.eccObject = value;
    }

    /**
     * Gets the value of the pwrObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwrObject() {
        return pwrObject;
    }

    /**
     * Sets the value of the pwrObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwrObject(String value) {
        this.pwrObject = value;
    }

}
