//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maxLinkWidth",
    "currentLinkWidth"
})
@XmlRootElement(name = "link_widths")
public class LinkWidths {

    @XmlElement(name = "max_link_width", required = true)
    protected String maxLinkWidth;
    @XmlElement(name = "current_link_width", required = true)
    protected String currentLinkWidth;

    /**
     * Gets the value of the maxLinkWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxLinkWidth() {
        return maxLinkWidth;
    }

    /**
     * Sets the value of the maxLinkWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxLinkWidth(String value) {
        this.maxLinkWidth = value;
    }

    /**
     * Gets the value of the currentLinkWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentLinkWidth() {
        return currentLinkWidth;
    }

    /**
     * Sets the value of the currentLinkWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentLinkWidth(String value) {
        this.currentLinkWidth = value;
    }

}
