//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "graphicsClock",
    "smClock",
    "memClock",
    "videoClock"
})
@XmlRootElement(name = "max_clocks")
public class MaxClocks {

    @XmlElement(name = "graphics_clock", required = true)
    protected String graphicsClock;
    @XmlElement(name = "sm_clock", required = true)
    protected String smClock;
    @XmlElement(name = "mem_clock", required = true)
    protected String memClock;
    @XmlElement(name = "video_clock", required = true)
    protected String videoClock;

    /**
     * Gets the value of the graphicsClock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGraphicsClock() {
        return graphicsClock;
    }

    /**
     * Sets the value of the graphicsClock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGraphicsClock(String value) {
        this.graphicsClock = value;
    }

    /**
     * Gets the value of the smClock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmClock() {
        return smClock;
    }

    /**
     * Sets the value of the smClock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmClock(String value) {
        this.smClock = value;
    }

    /**
     * Gets the value of the memClock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemClock() {
        return memClock;
    }

    /**
     * Sets the value of the memClock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemClock(String value) {
        this.memClock = value;
    }

    /**
     * Gets the value of the videoClock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideoClock() {
        return videoClock;
    }

    /**
     * Sets the value of the videoClock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideoClock(String value) {
        this.videoClock = value;
    }

}
