//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "retiredCount",
    "retiredPageAddresses"
})
@XmlRootElement(name = "multiple_single_bit_retirement")
public class MultipleSingleBitRetirement {

    @XmlElement(name = "retired_count", required = true)
    protected String retiredCount;
    @XmlElement(name = "retired_page_addresses", required = true)
    protected String retiredPageAddresses;

    /**
     * Gets the value of the retiredCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetiredCount() {
        return retiredCount;
    }

    /**
     * Sets the value of the retiredCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetiredCount(String value) {
        this.retiredCount = value;
    }

    /**
     * Gets the value of the retiredPageAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetiredPageAddresses() {
        return retiredPageAddresses;
    }

    /**
     * Sets the value of the retiredPageAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetiredPageAddresses(String value) {
        this.retiredPageAddresses = value;
    }

}
