//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClocksThrottleReasonGpuIdle }
     * 
     */
    public ClocksThrottleReasonGpuIdle createClocksThrottleReasonGpuIdle() {
        return new ClocksThrottleReasonGpuIdle();
    }

    /**
     * Create an instance of {@link PcieGen }
     * 
     */
    public PcieGen createPcieGen() {
        return new PcieGen();
    }

    /**
     * Create an instance of {@link FbMemoryUsage }
     * 
     */
    public FbMemoryUsage createFbMemoryUsage() {
        return new FbMemoryUsage();
    }

    /**
     * Create an instance of {@link ClocksThrottleReasonUnknown }
     * 
     */
    public ClocksThrottleReasonUnknown createClocksThrottleReasonUnknown() {
        return new ClocksThrottleReasonUnknown();
    }

    /**
     * Create an instance of {@link ApplicationsClocks }
     * 
     */
    public ApplicationsClocks createApplicationsClocks() {
        return new ApplicationsClocks();
    }

    /**
     * Create an instance of {@link EccMode }
     * 
     */
    public EccMode createEccMode() {
        return new EccMode();
    }

    /**
     * Create an instance of {@link DoubleBitRetirement }
     * 
     */
    public DoubleBitRetirement createDoubleBitRetirement() {
        return new DoubleBitRetirement();
    }

    /**
     * Create an instance of {@link InforomVersion }
     * 
     */
    public InforomVersion createInforomVersion() {
        return new InforomVersion();
    }

    /**
     * Create an instance of {@link MaxClocks }
     * 
     */
    public MaxClocks createMaxClocks() {
        return new MaxClocks();
    }

    /**
     * Create an instance of {@link ClocksThrottleReasonHwSlowdown }
     * 
     */
    public ClocksThrottleReasonHwSlowdown createClocksThrottleReasonHwSlowdown() {
        return new ClocksThrottleReasonHwSlowdown();
    }

    /**
     * Create an instance of {@link Utilization }
     * 
     */
    public Utilization createUtilization() {
        return new Utilization();
    }

    /**
     * Create an instance of {@link Clocks }
     * 
     */
    public Clocks createClocks() {
        return new Clocks();
    }

    /**
     * Create an instance of {@link PciGpuLinkInfo }
     * 
     */
    public PciGpuLinkInfo createPciGpuLinkInfo() {
        return new PciGpuLinkInfo();
    }

    /**
     * Create an instance of {@link LinkWidths }
     * 
     */
    public LinkWidths createLinkWidths() {
        return new LinkWidths();
    }

    /**
     * Create an instance of {@link GpuVirtualizationMode }
     * 
     */
    public GpuVirtualizationMode createGpuVirtualizationMode() {
        return new GpuVirtualizationMode();
    }

    /**
     * Create an instance of {@link PciBridgeChip }
     * 
     */
    public PciBridgeChip createPciBridgeChip() {
        return new PciBridgeChip();
    }

    /**
     * Create an instance of {@link RetiredPages }
     * 
     */
    public RetiredPages createRetiredPages() {
        return new RetiredPages();
    }

    /**
     * Create an instance of {@link MultipleSingleBitRetirement }
     * 
     */
    public MultipleSingleBitRetirement createMultipleSingleBitRetirement() {
        return new MultipleSingleBitRetirement();
    }

    /**
     * Create an instance of {@link DefaultApplicationsClocks }
     * 
     */
    public DefaultApplicationsClocks createDefaultApplicationsClocks() {
        return new DefaultApplicationsClocks();
    }

    /**
     * Create an instance of {@link InforomChecksum }
     * 
     */
    public InforomChecksum createInforomChecksum() {
        return new InforomChecksum();
    }

    /**
     * Create an instance of {@link Temperature }
     * 
     */
    public Temperature createTemperature() {
        return new Temperature();
    }

    /**
     * Create an instance of {@link SupportedGraphicsClock }
     * 
     */
    public SupportedGraphicsClock createSupportedGraphicsClock() {
        return new SupportedGraphicsClock();
    }

    /**
     * Create an instance of {@link PowerReadings }
     * 
     */
    public PowerReadings createPowerReadings() {
        return new PowerReadings();
    }

    /**
     * Create an instance of {@link MaxCustomerBoostClocks }
     * 
     */
    public MaxCustomerBoostClocks createMaxCustomerBoostClocks() {
        return new MaxCustomerBoostClocks();
    }

    /**
     * Create an instance of {@link Gpu }
     * 
     */
    public Gpu createGpu() {
        return new Gpu();
    }

    /**
     * Create an instance of {@link DriverModel }
     * 
     */
    public DriverModel createDriverModel() {
        return new DriverModel();
    }

    /**
     * Create an instance of {@link GpuOperationMode }
     * 
     */
    public GpuOperationMode createGpuOperationMode() {
        return new GpuOperationMode();
    }

    /**
     * Create an instance of {@link Pci }
     * 
     */
    public Pci createPci() {
        return new Pci();
    }

    /**
     * Create an instance of {@link Bar1MemoryUsage }
     * 
     */
    public Bar1MemoryUsage createBar1MemoryUsage() {
        return new Bar1MemoryUsage();
    }

    /**
     * Create an instance of {@link EncoderStats }
     * 
     */
    public EncoderStats createEncoderStats() {
        return new EncoderStats();
    }

    /**
     * Create an instance of {@link EccErrors }
     * 
     */
    public EccErrors createEccErrors() {
        return new EccErrors();
    }

    /**
     * Create an instance of {@link ClockPolicy }
     * 
     */
    public ClockPolicy createClockPolicy() {
        return new ClockPolicy();
    }

    /**
     * Create an instance of {@link ClocksThrottleReasonSwPowerCap }
     * 
     */
    public ClocksThrottleReasonSwPowerCap createClocksThrottleReasonSwPowerCap() {
        return new ClocksThrottleReasonSwPowerCap();
    }

    /**
     * Create an instance of {@link Volatile }
     * 
     */
    public Volatile createVolatile() {
        return new Volatile();
    }

    /**
     * Create an instance of {@link Aggregate }
     * 
     */
    public Aggregate createAggregate() {
        return new Aggregate();
    }

    /**
     * Create an instance of {@link NvidiaSmiLog }
     * 
     */
    public NvidiaSmiLog createNvidiaSmiLog() {
        return new NvidiaSmiLog();
    }

    /**
     * Create an instance of {@link ProcessInfo }
     * 
     */
    public ProcessInfo createProcessInfo() {
        return new ProcessInfo();
    }

    /**
     * Create an instance of {@link SingleBit }
     * 
     */
    public SingleBit createSingleBit() {
        return new SingleBit();
    }

    /**
     * Create an instance of {@link DoubleBit }
     * 
     */
    public DoubleBit createDoubleBit() {
        return new DoubleBit();
    }

    /**
     * Create an instance of {@link ClocksThrottleReasonSyncBoost }
     * 
     */
    public ClocksThrottleReasonSyncBoost createClocksThrottleReasonSyncBoost() {
        return new ClocksThrottleReasonSyncBoost();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link SupportedMemClock }
     * 
     */
    public SupportedMemClock createSupportedMemClock() {
        return new SupportedMemClock();
    }

    /**
     * Create an instance of {@link ClocksThrottleReasonApplicationsClocksSetting }
     * 
     */
    public ClocksThrottleReasonApplicationsClocksSetting createClocksThrottleReasonApplicationsClocksSetting() {
        return new ClocksThrottleReasonApplicationsClocksSetting();
    }

    /**
     * Create an instance of {@link RetiredPageAddress }
     * 
     */
    public RetiredPageAddress createRetiredPageAddress() {
        return new RetiredPageAddress();
    }

    /**
     * Create an instance of {@link AccountedProcessInfo }
     * 
     */
    public AccountedProcessInfo createAccountedProcessInfo() {
        return new AccountedProcessInfo();
    }

}
