//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bridgeChipType",
    "bridgeChipFw"
})
@XmlRootElement(name = "pci_bridge_chip")
public class PciBridgeChip {

    @XmlElement(name = "bridge_chip_type", required = true)
    protected String bridgeChipType;
    @XmlElement(name = "bridge_chip_fw", required = true)
    protected String bridgeChipFw;

    /**
     * Gets the value of the bridgeChipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBridgeChipType() {
        return bridgeChipType;
    }

    /**
     * Sets the value of the bridgeChipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBridgeChipType(String value) {
        this.bridgeChipType = value;
    }

    /**
     * Gets the value of the bridgeChipFw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBridgeChipFw() {
        return bridgeChipFw;
    }

    /**
     * Sets the value of the bridgeChipFw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBridgeChipFw(String value) {
        this.bridgeChipFw = value;
    }

}
