//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maxLinkGen",
    "currentLinkGen"
})
@XmlRootElement(name = "pcie_gen")
public class PcieGen {

    @XmlElement(name = "max_link_gen", required = true)
    protected String maxLinkGen;
    @XmlElement(name = "current_link_gen", required = true)
    protected String currentLinkGen;

    /**
     * Gets the value of the maxLinkGen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxLinkGen() {
        return maxLinkGen;
    }

    /**
     * Sets the value of the maxLinkGen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxLinkGen(String value) {
        this.maxLinkGen = value;
    }

    /**
     * Gets the value of the currentLinkGen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentLinkGen() {
        return currentLinkGen;
    }

    /**
     * Sets the value of the currentLinkGen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentLinkGen(String value) {
        this.currentLinkGen = value;
    }

}
