//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pcieGen",
    "linkWidths"
})
@XmlRootElement(name = "pci_gpu_link_info")
public class PciGpuLinkInfo {

    @XmlElement(name = "pcie_gen", required = true)
    protected PcieGen pcieGen;
    @XmlElement(name = "link_widths", required = true)
    protected LinkWidths linkWidths;

    /**
     * Gets the value of the pcieGen property.
     * 
     * @return
     *     possible object is
     *     {@link PcieGen }
     *     
     */
    public PcieGen getPcieGen() {
        return pcieGen;
    }

    /**
     * Sets the value of the pcieGen property.
     * 
     * @param value
     *     allowed object is
     *     {@link PcieGen }
     *     
     */
    public void setPcieGen(PcieGen value) {
        this.pcieGen = value;
    }

    /**
     * Gets the value of the linkWidths property.
     * 
     * @return
     *     possible object is
     *     {@link LinkWidths }
     *     
     */
    public LinkWidths getLinkWidths() {
        return linkWidths;
    }

    /**
     * Sets the value of the linkWidths property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkWidths }
     *     
     */
    public void setLinkWidths(LinkWidths value) {
        this.linkWidths = value;
    }

}
