//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "multipleSingleBitRetirement",
    "doubleBitRetirement",
    "pendingRetirement"
})
@XmlRootElement(name = "retired_pages")
public class RetiredPages {

    @XmlElement(name = "multiple_single_bit_retirement", required = true)
    protected MultipleSingleBitRetirement multipleSingleBitRetirement;
    @XmlElement(name = "double_bit_retirement", required = true)
    protected DoubleBitRetirement doubleBitRetirement;
    @XmlElement(name = "pending_retirement", required = true)
    protected String pendingRetirement;

    /**
     * Gets the value of the multipleSingleBitRetirement property.
     * 
     * @return
     *     possible object is
     *     {@link MultipleSingleBitRetirement }
     *     
     */
    public MultipleSingleBitRetirement getMultipleSingleBitRetirement() {
        return multipleSingleBitRetirement;
    }

    /**
     * Sets the value of the multipleSingleBitRetirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultipleSingleBitRetirement }
     *     
     */
    public void setMultipleSingleBitRetirement(MultipleSingleBitRetirement value) {
        this.multipleSingleBitRetirement = value;
    }

    /**
     * Gets the value of the doubleBitRetirement property.
     * 
     * @return
     *     possible object is
     *     {@link DoubleBitRetirement }
     *     
     */
    public DoubleBitRetirement getDoubleBitRetirement() {
        return doubleBitRetirement;
    }

    /**
     * Sets the value of the doubleBitRetirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleBitRetirement }
     *     
     */
    public void setDoubleBitRetirement(DoubleBitRetirement value) {
        this.doubleBitRetirement = value;
    }

    /**
     * Gets the value of the pendingRetirement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPendingRetirement() {
        return pendingRetirement;
    }

    /**
     * Sets the value of the pendingRetirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPendingRetirement(String value) {
        this.pendingRetirement = value;
    }

}
