//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "valueOrSupportedGraphicsClock"
})
@XmlRootElement(name = "supported_mem_clock")
public class SupportedMemClock {

    @XmlElements({
        @XmlElement(name = "value", type = Value.class),
        @XmlElement(name = "supported_graphics_clock", type = SupportedGraphicsClock.class)
    })
    protected List<Object> valueOrSupportedGraphicsClock;

    /**
     * Gets the value of the valueOrSupportedGraphicsClock property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valueOrSupportedGraphicsClock property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValueOrSupportedGraphicsClock().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Value }
     * {@link SupportedGraphicsClock }
     * 
     * 
     */
    public List<Object> getValueOrSupportedGraphicsClock() {
        if (valueOrSupportedGraphicsClock == null) {
            valueOrSupportedGraphicsClock = new ArrayList<Object>();
        }
        return this.valueOrSupportedGraphicsClock;
    }

}
