//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gpuTemp",
    "gpuTempMaxThreshold",
    "gpuTempSlowThreshold",
    "memoryTemp"
})
@XmlRootElement(name = "temperature")
public class Temperature {

    @XmlElement(name = "gpu_temp", required = true)
    protected String gpuTemp;
    @XmlElement(name = "gpu_temp_max_threshold", required = true)
    protected String gpuTempMaxThreshold;
    @XmlElement(name = "gpu_temp_slow_threshold", required = true)
    protected String gpuTempSlowThreshold;
    @XmlElement(name = "memory_temp", required = true)
    protected String memoryTemp;

    /**
     * Gets the value of the gpuTemp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpuTemp() {
        return gpuTemp;
    }

    /**
     * Sets the value of the gpuTemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpuTemp(String value) {
        this.gpuTemp = value;
    }

    /**
     * Gets the value of the gpuTempMaxThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpuTempMaxThreshold() {
        return gpuTempMaxThreshold;
    }

    /**
     * Sets the value of the gpuTempMaxThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpuTempMaxThreshold(String value) {
        this.gpuTempMaxThreshold = value;
    }

    /**
     * Gets the value of the gpuTempSlowThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpuTempSlowThreshold() {
        return gpuTempSlowThreshold;
    }

    /**
     * Sets the value of the gpuTempSlowThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpuTempSlowThreshold(String value) {
        this.gpuTempSlowThreshold = value;
    }

    /**
     * Gets the value of the memoryTemp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemoryTemp() {
        return memoryTemp;
    }

    /**
     * Sets the value of the memoryTemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemoryTemp(String value) {
        this.memoryTemp = value;
    }

}
