//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.11 at 04:03:19 PM EET 
//


package com.chaos.crypto.ewbf.watchdog.nvidia.sli.dtd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gpuUtil",
    "memoryUtil",
    "encoderUtil",
    "decoderUtil"
})
@XmlRootElement(name = "utilization")
public class Utilization {

    @XmlElement(name = "gpu_util", required = true)
    protected String gpuUtil;
    @XmlElement(name = "memory_util", required = true)
    protected String memoryUtil;
    @XmlElement(name = "encoder_util", required = true)
    protected String encoderUtil;
    @XmlElement(name = "decoder_util", required = true)
    protected String decoderUtil;

    /**
     * Gets the value of the gpuUtil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpuUtil() {
        return gpuUtil;
    }

    /**
     * Sets the value of the gpuUtil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpuUtil(String value) {
        this.gpuUtil = value;
    }

    /**
     * Gets the value of the memoryUtil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemoryUtil() {
        return memoryUtil;
    }

    /**
     * Sets the value of the memoryUtil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemoryUtil(String value) {
        this.memoryUtil = value;
    }

    /**
     * Gets the value of the encoderUtil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncoderUtil() {
        return encoderUtil;
    }

    /**
     * Sets the value of the encoderUtil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncoderUtil(String value) {
        this.encoderUtil = value;
    }

    /**
     * Gets the value of the decoderUtil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecoderUtil() {
        return decoderUtil;
    }

    /**
     * Sets the value of the decoderUtil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecoderUtil(String value) {
        this.decoderUtil = value;
    }

}
